grade:
	gcc -o grade.o Grade.c -Wall -lm

delimiter:
	gcc -o delim.o Delimiter.c -Wall -lm

tracing1:
	gcc -o trace1.o Tracing1.c -Wall -lm

tracing2:
	gcc -o trace2.o Tracing2.c -Wall -lm

pointers:
	gcc -o point.o Pointers.c -Wall -lm

all:
	gcc -o grade.o Grade.c -Wall -lm
	gcc -o delim.o Delimiter.c -Wall -lm
	gcc -o point.o Pointers.c -Wall -lm
	gcc -o trace1.o Tracing1.c -Wall -lm
	gcc -o trace2.o Tracing2.c -Wall -lm
clean:
	rm *.o