grade:
	gcc -o grade.o Grade.c -Wall -lm

delimiter:
	gcc -o delim.o Delimiter.c -Wall -lm

tracing1:
	gcc -o trace1.o Tracing1.c -Wall -lm

tracing2:
	gcc -o trace2.o Tracing2.c -Wall -lm

pointers:
	gcc -o point.o Pointers.c -Wall -lm

all:
	make grade
	make delimiter
	make pointers
	make tracing1
	make tracing2

clean:
	rm *.o