cashback:
	gcc -o cash.o Cashback.c -Wall -lm

safe:
	gcc -o safe.o Safe.c -Wall -lm

recurse:
	gcc -o rec1.o TraceRecursion1.c -Wall -lm	
	gcc -o rec2.o TraceRecursion2.c -Wall -lm

all:
	gcc -o cash.o Cashback.c -Wall -lm
	gcc -o safe.o Safe.c -Wall -lm
	gcc -o rec1.o TraceRecursion1.c -Wall -lm	
	gcc -o rec2.o TraceRecursion2.c -Wall -lm

clean:
	rm *.o

