caesar:
	gcc -o caes.o Caesar.c -Wall -lm

cpa:
	gcc -o cpa.o CPA.c -Wall -lm

mat:
	gcc -o mat.o MatrixMult.c -Wall -lm

all:
	gcc -o caes.o Caesar.c -Wall -lm
	gcc -o mat.o MatrixMult.c -Wall -lm
	gcc -o cpa.o CPA.c -Wall -lm
	
clean:
	rm *.o
