board1:
	gcc -o board1.o Board1.c -Wall -lm
board2:
	gcc -o board2.o Board2.c -Wall -lm
prime:
	gcc -o prime.o Prime.c -Wall -lm
trace:
	gcc -o trace.o Tracing.c -Wall -lm
all:
	make trace
	make board1
	make board2
	make prime