pixel:
	gcc -o pix.o Pixel.c -Wall -lm

convert:
	gcc -o conv.o Convert.c -Wall -lm

passing:
	gcc -o ptr.o PassingPointer.c -Wall -lm

all:
	gcc -o pix.o Pixel.c -Wall -lm
	gcc -o ptr.o PassingPointer.c -Wall -lm
	gcc -o conv.o Convert.c -Wall -lm

clean:
	rm *.o
