anagram:
	gcc -o ana.o Anagram.c -Wall -lm

equation:
	gcc -o equ.o Equation.c -Wall -lm

over:
	gcc -o over.o Overflow.c -Wall -lm -fno-stack-protector

all:
	gcc -o ana.o Anagram.c -Wall -lm
	gcc -o equ.o Equation.c -Wall -lm

clean:
	rm *.o
