
zero:
	gcc -o zero.o DivideByZero.c -Wall

assign:
	gcc -o assign.o AssignOrder.c -Wall

freezer:
	gcc -o freeze.o Freezer.c -lm -Wall

parity:
	gcc -o par.o Parity.c -lm -Wall

all:
	make zero
	make assign
	make freezer
	make parity