olympic:
	gcc -o olympic.o Olympic.c -Wall -lm

olympic2:
	gcc -o olympic2.o Olympic2.c -Wall -lm

arithmetic:
	gcc -o arith.o Arithmetic.c -Wall -lm

struct:
	gcc -o struct.o StructExample.c -Wall -lm	

all:
	gcc -o olympic.o Olympic.c -Wall -lm
	gcc -o struct.o StructExample.c -Wall -lm
	gcc -o arith.o Arithmetic.c -Wall -lm
	gcc -o olympic2.o Olympic2.c -Wall -lm

clean:
	rm *.o
