olympic:
	gcc -o olympic.o Olympic.c -Wall -lm

olympic2:
	gcc -o olympic2.o Olympic2.c -Wall -lm

arithmetic:
	gcc -o arith.o Arithmetic.c -Wall -lm

struct:
	gcc -o struct.o StructExample.c -Wall -lm	

all:
	make olympic
	make struct
	make arithmetic
	make olympic2

clean:
	rm *.o
